# 创建数据库
CREATE DATABASE `lightBBS`;
USE `lightBBS`;

# 创建用户表,密码盐由md5(随机字母)生成 role默认值为user表示普通用户，admin表示管理员用户
CREATE TABLE `bbs_user` (
 `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '用户id',
 `name` VARCHAR(100) NOT NULL UNIQUE DEFAULT '' COMMENT '用户名',
 `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
 `salt` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码盐',
 `email` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '邮箱',
 `is_active` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮箱是否激活,0-未激活,1-已激活',
 `role` VARCHAR(100) NOT NULL DEFAULT 'user' COMMENT '用户角色',
 `img_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像地址',
 `reg_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
 `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# 创建主题分类表
CREATE TABLE `bbs_category` (
 `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '分类id',
 `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '名称',
 `sort` INT NOT NULL DEFAULT 0 COMMENT '排序',
 `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# 创建主题表
CREATE TABLE `bbs_topic` (
 `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主题id',
 `title` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '名称',
 `category_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '分类id',
 `content` TEXT NOT NULL COMMENT '回复内容',
 `user_id` INT UNSIGNED NOT NULL DEFAULT 0  COMMENT '用户id',
 `is_show` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否显示',
 `hits` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点击量',
 `likenum` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞量',
 `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  KEY ix_category (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


# 创建回复表
CREATE TABLE `bbs_reply` (
 `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '回复id',
 `topic_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '主题id',
 `content` TEXT NOT NULL COMMENT '回复内容',
 `user_id` INT UNSIGNED NOT NULL DEFAULT 0  COMMENT '用户id',
 `is_show` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否显示',
 `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复时间',
 `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `bbs_user`(`name`,`password`,`salt`,`email`,`role`) VALUES
('admin',MD5(CONCAT(MD5('123456'), MD5('AXVED'))),MD5('AXVED'),'990198829@qq.com','admin');



